name: Static Analysis & Tests

on:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  check-code:
    name: Check code
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: src    
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install development dependencies
        run: |
          python3 -m pip install .[dev]

      - name: Lint with Pylint
        run: pylint $PROJECT_DIR

      - name: Check formatting with Black
        run: black --check $PROJECT_DIR

      - name: Check imports with Isort
        run: isort --check $PROJECT_DIR

      - name: Install test dependencies
        run: python3 -m pip install .[test]

      - name: Test with Pytest
        run: pytest
